version: '3.8'

services:
  tv-api:
    build: .
    container_name: tv-api-container
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://admin:password@192.168.1.100:27017/tvapp
      - PORT=3001
      - ENABLE_SWAGGER=true
    restart: unless-stopped
