version: '3.8'

services:
  tv-api:
    build: .
    container_name: tv-api-container
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://dmoir:zsedcx.123.zx@cluster0.iqrs2ax.mongodb.net/tvapp?retryWrites=true&w=majority&appName=Cluster0
      - PORT=3001
      - ENABLE_SWAGGER=true
    restart: unless-stopped
    networks:
      - tv-network

  cloudflared-api:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-api-tv
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiOWExOGZhZjlkM2I1MWRkOTM4ODhhNmYzNTY3MzdjNzEiLCJ0IjoiYjM3ODkxMzUtMjI2Mi00ZTYwLWE0NDktYzc0MWUzNTA4MmI0IiwicyI6IlpXRTJOemM0TXprdFpqY3hNUzAwTWpobUxUZ3paV010WXpKbU0yUXpOVEUxTlRjeSJ9
    networks:
      - tv-network

networks:
  tv-network:
    name: tv-network
    driver: bridge
