version: '3.8'

services:
  tv-api:
    build: .
    container_name: tv-api-container
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb+srv://dmoir:zsedcx.123.zx@cluster0.iqrs2ax.mongodb.net/tvapp?retryWrites=true&w=majority&appName=Cluster0
      - PORT=3001
      - ENABLE_SWAGGER=true
    restart: unless-stopped
